### ISSUE TITLE
Helpers for scroll position restoration 

### ISSUE THREAD

**Issue by MrLoh** [faceyspacey/redux-first-router-navigation#3]
It would be great to have some help with scroll position restoration. Scenario: I'm on one tab and scroll down 100px, I change to another tab, and then return to the first tab, the first tab should still be scrolled to 100px. This would require to store the scroll position somewhere, I'm not sure how this could be handled best.

**Comment by faceyspacey** [comment]
The docs have a scroll container component for native. 

https://github.com/faceyspacey/redux-first-router/blob/master/docs/scroll-restoration.md#scroll-restoration-for-react-native

u probably didnt see it cuz it's in the regular web scroll restoration doc.

Let me know if that works for you.

**Comment by MrLoh** [comment]
Looks great. I'll definitely try that.
